/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/CRTMonitor.glb -T -t -s -E -o src/components/CRTMonitor.tsx 
Files: public/models/CRTMonitor.glb [52.56KB] > C:\Users\User\IdeaProjects\blog\src\components\CRTMonitor-transformed.glb [7.16KB] (86%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Node-Mesh']: THREE.Mesh
    ['Node-Mesh_1']: THREE.Mesh
    ['Node-Mesh_2']: THREE.Mesh
    ['Node-Mesh_3']: THREE.Mesh
  }
  materials: {
    mat15: THREE.MeshStandardMaterial
    mat17: THREE.MeshStandardMaterial
    mat16: THREE.MeshStandardMaterial
    mat22: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/CRTMonitor-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes['Node-Mesh'].geometry} material={materials.mat15} />
      <mesh castShadow receiveShadow geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat17} />
      <mesh castShadow receiveShadow geometry={nodes['Node-Mesh_2'].geometry} material={materials.mat16} />
      <mesh castShadow receiveShadow geometry={nodes['Node-Mesh_3'].geometry} material={materials.mat22} />
    </group>
  )
}

useGLTF.preload('/models/CRTMonitor-transformed.glb')
