/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/FeaturedContent.glb -T -t -s -E -o src/components/FeaturedContent.tsx 
Files: public/models/FeaturedContent.glb [116.07KB] > C:\Users\User\IdeaProjects\blog\src\components\FeaturedContent-transformed.glb [9.03KB] (92%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    group1078865745: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/FeaturedContent-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.group1078865745.geometry} material={materials.PaletteMaterial001} />
    </group>
  )
}

useGLTF.preload('/models/FeaturedContent-transformed.glb')
