/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/GameBoy.glb -T -j -t -s -E -o src/components/GameBoy.tsx 
Files: public/models/GameBoy.glb [2.67MB] > C:\Users\User\IdeaProjects\blog\src\components\GameBoy-transformed.glb [69.01KB] (97%)
*/

import * as THREE from 'three'
import React, {type JSX} from 'react'
import {useGLTF} from '@react-three/drei'
import {type GLTF} from 'three-stdlib'

type GLTFResult = GLTF & {
    nodes: {
        GameBoy: THREE.Mesh
        A: THREE.Mesh
        B: THREE.Mesh
        ['+']: THREE.Mesh
        ['2']: THREE.Mesh
        ['1']: THREE.Mesh
    }
    materials: {
        lambert2SG: THREE.MeshPhysicalMaterial
    }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
    const {nodes, materials} = useGLTF('/models/GameBoy-transformed.glb') as unknown as GLTFResult
    return (
        <group {...props} dispose={null}>
            <mesh castShadow receiveShadow geometry={nodes.GameBoy.geometry} material={materials.lambert2SG} rotation={[Math.PI / 2, 0, 0]}/>
            <mesh castShadow receiveShadow geometry={nodes.A.geometry} material={materials.lambert2SG} rotation={[Math.PI / 2, 0, 0]}/>
            <mesh castShadow receiveShadow geometry={nodes.B.geometry} material={materials.lambert2SG} rotation={[Math.PI / 2, 0, 0]}/>
            <mesh castShadow receiveShadow geometry={nodes['+'].geometry} material={materials.lambert2SG} rotation={[Math.PI / 2, 0, 0]}/>
            <mesh castShadow receiveShadow geometry={nodes['2'].geometry} material={materials.lambert2SG} rotation={[Math.PI / 2, 0, 0]}/>
            <mesh castShadow receiveShadow geometry={nodes['1'].geometry} material={materials.lambert2SG} rotation={[Math.PI / 2, 0, 0]}/>
        </group>
    )
}

useGLTF.preload('/models/GameBoy-transformed.glb')
