/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Radio.glb --transform -t -o src/components/Radio.tsx 
Files: public/models/Radio.glb [29KB] > C:\Users\User\IdeaProjects\blog\src\components\Radio-transformed.glb [6.1KB] (79%)
*/

import * as THREE from 'three'
import React from 'react'
import {useGLTF} from '@react-three/drei'
import {type GLTF} from 'three-stdlib'

type GLTFResult = GLTF & {
    nodes: {
        Radio_1: THREE.Mesh
        Radio_2: THREE.Mesh
        Radio_3: THREE.Mesh
        Radio_4: THREE.Mesh
    }
    materials: {
        Black: THREE.MeshStandardMaterial
        DarkGrey: THREE.MeshStandardMaterial
        LightGrey: THREE.MeshStandardMaterial
        Red: THREE.MeshStandardMaterial
    }
    animations: GLTFAction[]
}

export function Radio(props: JSX.IntrinsicElements['group']) {
    const {nodes, materials} = useGLTF('/models/Radio-transformed.glb') as GLTFResult
    return (
        <group castShadow {...props} dispose={null}>
            <group castShadow rotation={[-Math.PI / 2, 0, 0]} scale={242.003}>
                <mesh castShadow receiveShadow geometry={nodes.Radio_1.geometry} material={materials.Black}/>
                <mesh castShadow receiveShadow geometry={nodes.Radio_2.geometry} material={materials.DarkGrey}/>
                <mesh castShadow receiveShadow geometry={nodes.Radio_3.geometry} material={materials.LightGrey}/>
                <mesh castShadow receiveShadow geometry={nodes.Radio_4.geometry}>
                    <meshStandardMaterial color={"#fb5320"}/>
                </mesh>
            </group>
        </group>
    )
}

useGLTF.preload('/models/Radio-transformed.glb')
