/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Videogame.glb -T -t -s -E -o src/components/Videogame.tsx 
Files: public/models/Videogame.glb [544.62KB] > C:\Users\User\IdeaProjects\blog\src\components\Videogame-transformed.glb [16.65KB] (97%)
*/

import * as THREE from 'three'
import React, {type JSX} from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    GameBoy_mesh: THREE.Mesh
  }
  materials: {
    lambert2SG: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Videogame-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.GameBoy_mesh.geometry} material={materials.lambert2SG} />
    </group>
  )
}

useGLTF.preload('/models/Videogame-transformed.glb')
